name: CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: Install nodejs dependencies
        run: |
          npm install
      - name: Run Webpack Build
        run: |
          npm run production
      - name: Commit
        run: |
          git config --local user.name "haidir32"
          git config --local user.email "haidir32@gmail.com"
          git add .
          git commit -m "[AUTO:BUILD] build from main.js" || echo "No changes to commit"
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: "main"
          repository: "mhaidir32/github-actions-test"